
# auto-generated by configure
PREFIX = /usr/local
VERSION = 2.4.1
CC = gcc
CFLAGS = -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -Wno-unknown-pragmas -mmacosx-version-min=10.6 -DUSE_COCOA=1 -I/opt/homebrew/opt/libpng/include/libpng16 
LDFLAGS =  -mmacosx-version-min=10.6 -framework Cocoa -L/opt/homebrew/opt/libpng/lib -lpng16 -lz -lm
COCOA_READER = 1

